// Public key used to verify license signatures (generated by tools/license-tool.mjs init)
module.exports = { PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAzklayCGgi2cYOguPNfatFJm7WrvuUZXeIdmeGh9mZJg=\n-----END PUBLIC KEY-----\n" };
