// Advanced question bank — smart / addressable fire-alarm systems, integration, ITM (EN / AR).
// Format matches src/data/quiz.js: { id, topic, q, options[], answer, explain }.
const Q = (id, topic, qen, qar, opts, answer, een, ear) => ({ id, topic, q: { en: qen, ar: qar }, options: opts.map(([en, ar]) => ({ en, ar })), answer, explain: { en: een, ar: ear } });

export const ADV_QUIZ = [
  Q('a1', 'slc', 'A Class A SLC loop has one open circuit. What happens?', 'حلقة SLC من الفئة A فيها قطع واحد. ماذا يحدث؟',
    [['All devices keep working; the panel reports an open-circuit trouble', 'تبقى كل الأجهزة تعمل وتبلّغ اللوحة عن عطل دائرة مفتوحة'], ['Devices after the break are lost', 'تُفقد الأجهزة بعد القطع'], ['The whole loop goes into alarm', 'تدخل الحلقة كلها في إنذار'], ['Nothing is reported', 'لا يتم الإبلاغ عن شيء']], 0,
    'Class A returns to the panel, which drives the loop from both ends; a single open is annunciated as trouble but no device is lost (NFPA 72 §12.3.3).', 'تعود الفئة A إلى اللوحة التي تغذي الحلقة من الطرفين؛ القطع الواحد يظهر كعطل دون فقدان أي جهاز.'),
  Q('a2', 'slc', 'What limits the effect of a short circuit on an addressable loop?', 'ما الذي يحدّ من أثر القصر على الحلقة المعنونة؟',
    [['End-of-line resistors', 'مقاومات نهاية الخط'], ['Short-circuit isolators', 'عوازل دائرة القصر'], ['Alarm verification', 'التحقق من الإنذار'], ['A bigger battery', 'بطارية أكبر']], 1,
    'Isolators on either side of the fault open, so only the section between them is lost.', 'تفتح العوازل على جانبي العطل فلا يُفقد إلا القسم بينها.'),
  Q('a3', 'slc', 'After replacing a detector the panel shows "Unprogrammed device 031". The correct action is:', 'بعد استبدال كاشف تظهر اللوحة "جهاز غير مبرمج 031". الإجراء الصحيح:',
    [['Disable address 031', 'تعطيل العنوان 031'], ['Program the device (auto-learn / edit config) and verify its type and label', 'برمجة الجهاز (تعلّم تلقائي/تعديل التهيئة) والتحقق من نوعه ووصفه'], ['Ignore it', 'تجاهله'], ['Reset the panel', 'إعادة ضبط اللوحة']], 1,
    'An unprogrammed device is not supervised for its function until it is in the configuration.', 'الجهاز غير المبرمج لا يعمل وظيفياً حتى يُضاف إلى التهيئة.'),
  Q('a4', 'slc', 'Two devices answer on address 017. The panel reports:', 'جهازان يستجيبان على العنوان 017. تُبلّغ اللوحة عن:',
    [['Double address trouble', 'عطل عنوان مكرر'], ['Fire alarm', 'إنذار حريق'], ['Ground fault', 'تسرّب أرضي'], ['Nothing', 'لا شيء']], 0,
    'Duplicate addresses corrupt communication; both devices are unreliable until readdressed.', 'العناوين المكررة تفسد الاتصال؛ الجهازان غير موثوقين حتى يعاد ضبط العنوان.'),
  Q('a5', 'detection', 'An analog smoke detector reaches 80 % of its alarm threshold. A smart panel typically indicates:', 'كاشف دخان تناظري وصل إلى 80% من حد الإنذار. تُظهر اللوحة الذكية عادة:',
    [['Fire', 'حريق'], ['Pre-alarm', 'إنذار مبكر'], ['Trouble', 'عطل'], ['Supervisory', 'إشرافي']], 1,
    'Pre-alarm gives staff time to investigate before the fire threshold.', 'الإنذار المبكر يعطي وقتاً للتحقق قبل حد الحريق.'),
  Q('a6', 'detection', 'Drift compensation in an analog detector:', 'تعويض الانجراف في الكاشف التناظري:',
    [['Makes it more sensitive when dirty', 'يجعله أكثر حساسية عند الاتساخ'], ['Adjusts the clean-air reference as the chamber gets dirty and warns at the limit', 'يعدّل مرجع الهواء النظيف مع اتساخ الحجرة ويحذّر عند الحد'], ['Cleans the chamber automatically', 'ينظف الحجرة تلقائياً'], ['Disables the detector', 'يعطّل الكاشف']], 1,
    'The panel shifts the baseline and raises a maintenance alert when compensation is exhausted.', 'تغيّر اللوحة الخط الأساسي وتطلق تنبيه صيانة عند استنفاد التعويض.'),
  Q('a7', 'detection', 'Maximum spacing of spot smoke detectors on a smooth flat ceiling (nominal):', 'أقصى تباعد لكواشف الدخان النقطية على سقف أملس مستوٍ (اسمياً):',
    [['6.1 m', '6.1 م'], ['9.1 m', '9.1 م'], ['12 m', '12 م'], ['15 m', '15 م']], 1,
    'NFPA 72 uses 9.1 m (30 ft) nominal with every point within 0.7 S of a detector.', 'يستخدم NFPA 72 مسافة 9.1 م اسمياً مع أن تكون كل نقطة ضمن 0.7 S من كاشف.'),
  Q('a8', 'detection', 'A smoke detector must be at least how far from a supply-air diffuser?', 'على أي مسافة على الأقل يجب أن يكون كاشف الدخان من فتحة تغذية الهواء؟',
    [['0.3 m', '0.3 م'], ['0.9 m', '0.9 م'], ['2 m', '2 م'], ['No requirement', 'لا يوجد متطلب']], 1,
    'NFPA 72 §17.7.4.3 — 3 ft (0.9 m) from supply diffusers.', 'NFPA 72 §17.7.4.3 — 3 قدم (0.9 م) من فتحات التغذية.'),
  Q('a9', 'ce', 'FM-200 release in a server room should be initiated by:', 'يجب أن يُطلق FM-200 في غرفة الخوادم بواسطة:',
    [['Any building fire alarm', 'أي إنذار حريق في المبنى'], ['One detector in the room', 'كاشف واحد في الغرفة'], ['Two detectors in separate zones (cross-zoning) with a time delay', 'كاشفين في منطقتين منفصلتين (متقاطع) مع تأخير زمني'], ['The BMS', 'نظام إدارة المبنى']], 2,
    'Cross-zoning prevents unwanted discharges; the delay allows evacuation and abort.', 'الكشف المتقاطع يمنع التفريغ غير المرغوب؛ والتأخير يسمح بالإخلاء والإيقاف.'),
  Q('a10', 'ce', 'Smoke in the PRIMARY-floor lift lobby: the lift is recalled to…', 'دخان في ردهة المصعد في الطابق الرئيسي: يُستدعى المصعد إلى…',
    [['The primary floor', 'الطابق الرئيسي'], ['The alternate floor', 'الطابق البديل'], ['The top floor', 'الطابق الأخير'], ['It keeps normal service', 'يبقى في الخدمة العادية']], 1,
    'NFPA 72 §21.3.14.2 / ASME A17.1: never recall into the lobby that is in alarm.', 'لا يُستدعى المصعد أبداً إلى الردهة التي فيها الإنذار.'),
  Q('a11', 'ce', 'A sprinkler valve tamper switch should cause:', 'مفتاح عبث صمام الرشاشات يجب أن يسبب:',
    [['Building evacuation', 'إخلاء المبنى'], ['A supervisory signal to the panel and monitoring station', 'إشارة إشرافية للوحة ومركز المراقبة'], ['FM-200 discharge', 'تفريغ FM-200'], ['Nothing', 'لا شيء']], 1,
    'Supervisory signals are reported but never sound evacuation.', 'تُبلّغ الإشارات الإشرافية ولكنها لا تُطلق الإخلاء.'),
  Q('a12', 'ce', 'Why do AHUs shut down on fire alarm?', 'لماذا تتوقف وحدات مناولة الهواء عند إنذار الحريق؟',
    [['To save energy', 'لتوفير الطاقة'], ['To stop the ductwork spreading smoke (NFPA 90A)', 'لمنع مجاري الهواء من نشر الدخان (NFPA 90A)'], ['To cool the fire', 'لتبريد الحريق'], ['It is optional', 'اختياري']], 1,
    'Recirculating systems would distribute smoke to other floors.', 'أنظمة إعادة التدوير ستوزع الدخان على الطوابق الأخرى.'),
  Q('a13', 'integration', 'Which BACnet object type best represents "Fire alarm on floor 2"?', 'أي نوع كائن BACnet يمثل "إنذار حريق في الطابق 2" بشكل أفضل؟',
    [['Analog Input', 'مدخل تناظري'], ['Binary Input', 'مدخل ثنائي'], ['Analog Output', 'مخرج تناظري'], ['Schedule', 'جدول زمني']], 1,
    'Binary inputs carry two-state status points (ACTIVE / INACTIVE).', 'المدخلات الثنائية تحمل نقاط حالة بحالتين.'),
  Q('a14', 'integration', 'The BMS in a smart building should, for life-safety functions…', 'يجب على نظام إدارة المبنى في وظائف السلامة…',
    [['Be the only path that shuts down AHUs in fire', 'أن يكون المسار الوحيد لإيقاف المكيفات في الحريق'], ['Monitor the fire system; the listed FACP relays perform the emergency control functions', 'أن يراقب نظام الحريق؛ وتقوم ريليهات اللوحة المعتمدة بوظائف التحكم الطارئ'], ['Reset the fire panel remotely', 'أن يعيد ضبط لوحة الحريق عن بُعد'], ['Silence alarms at night', 'أن يُسكت الإنذارات ليلاً']], 1,
    'Emergency control functions must be performed through listed fire-alarm equipment (NFPA 72 §21.2).', 'يجب أداء وظائف التحكم الطارئ عبر معدات إنذار حريق معتمدة.'),
  Q('a15', 'integration', 'Contact-ID message "4721 18 1110 01 036" means:', 'رسالة Contact-ID "4721 18 1110 01 036" تعني:',
    [['Restore of fire alarm on zone 036', 'عودة إنذار الحريق في المنطقة 036'], ['New fire alarm on zone / point 036', 'إنذار حريق جديد في المنطقة/النقطة 036'], ['Trouble on zone 036', 'عطل في المنطقة 036'], ['Test signal', 'إشارة اختبار']], 1,
    'Qualifier 1 = new event, code 110 = fire.', 'المؤهل 1 = حدث جديد، الرمز 110 = حريق.'),
  Q('a16', 'integration', 'Phase II firefighter lift operation: the doors open when…', 'في المرحلة الثانية لتشغيل المصعد لرجال الإطفاء تُفتح الأبواب عندما…',
    [['The car arrives', 'يصل المصعد'], ['The DOOR OPEN button is held continuously until fully open', 'يُضغط زر فتح الباب باستمرار حتى يُفتح بالكامل'], ['The BMS commands it', 'يأمر بذلك نظام إدارة المبنى'], ['Smoke is detected', 'يُكتشف دخان']], 1,
    'Constant-pressure operation lets the firefighter close the doors instantly if smoke/fire is present.', 'التشغيل بالضغط المستمر يسمح لرجل الإطفاء بإغلاق الأبواب فوراً عند وجود دخان.'),
  Q('a17', 'voice', 'In phased evacuation of a high-rise, who receives the EVACUATE message first?', 'في الإخلاء المرحلي لمبنى عالٍ، من يتلقى رسالة الإخلاء أولاً؟',
    [['All floors', 'كل الطوابق'], ['The fire floor and the floor(s) above (and often below)', 'طابق الحريق والطوابق فوقه (وغالباً التي تحته)'], ['Only the ground floor', 'الطابق الأرضي فقط'], ['Only the top floor', 'الطابق الأخير فقط']], 1,
    'Other floors get an alert message to limit stair congestion.', 'تتلقى الطوابق الأخرى رسالة تنبيه للحد من ازدحام الدرج.'),
  Q('a18', 'voice', 'Minimum audible signal level in public mode (above average ambient):', 'الحد الأدنى لمستوى الصوت في الوضع العام (فوق المتوسط المحيط):',
    [['5 dB', '5 ديسيبل'], ['10 dB', '10 ديسيبل'], ['15 dB', '15 ديسيبل'], ['30 dB', '30 ديسيبل']], 2,
    'NFPA 72 §18.4.4: 15 dB above average ambient sound level, max 110 dBA.', 'NFPA 72 §18.4.4: 15 ديسيبل فوق متوسط الصوت المحيط، بحد أقصى 110.'),
  Q('a19', 'itm', 'Sensitivity testing of smoke detectors (after the first year) is required:', 'اختبار حساسية كواشف الدخان (بعد السنة الأولى) مطلوب:',
    [['Monthly', 'شهرياً'], ['Every 2 years (then per results, up to 5 years)', 'كل سنتين (ثم حسب النتائج حتى 5 سنوات)'], ['Every 10 years', 'كل 10 سنوات'], ['Never', 'أبداً']], 1,
    'NFPA 72 §14.4.4.3.', 'NFPA 72 §14.4.4.3.'),
  Q('a20', 'itm', 'Waterflow alarm-initiating devices must signal within:', 'أجهزة إنذار تدفق المياه يجب أن تعطي إشارة خلال:',
    [['10 s', '10 ث'], ['30 s', '30 ث'], ['90 s', '90 ث'], ['5 min', '5 دقائق']], 2,
    'NFPA 72 Table 14.4.3.2 / §17.13.2 — within 90 s of flow through the inspector\'s test.', 'خلال 90 ثانية من التدفق عبر صمام اختبار المفتش.'),
  Q('a21', 'itm', 'Standby battery capacity for a fire alarm system (non-voice):', 'سعة بطارية الاستعداد لنظام إنذار الحريق (بدون صوت):',
    [['4 h standby + 5 min alarm', '4 ساعات + 5 دقائق إنذار'], ['24 h standby + 5 min alarm', '24 ساعة استعداد + 5 دقائق إنذار'], ['24 h standby + 15 min alarm', '24 ساعة + 15 دقيقة'], ['72 h standby', '72 ساعة']], 1,
    'NFPA 72 §10.6.7.2.1 (voice EVAC needs 15 min alarm).', 'NFPA 72 §10.6.7.2.1 (الإخلاء الصوتي يحتاج 15 دقيقة إنذار).'),
  Q('a22', 'itm', 'A fire protection impairment (system out of service) requires first of all:', 'تعطيل نظام الحماية من الحريق (خارج الخدمة) يتطلب أولاً:',
    [['Nothing if it is short', 'لا شيء إذا كان قصيراً'], ['Impairment coordinator, notifications (AHJ, insurer, occupants) and a fire watch', 'منسق التعطيل والإشعارات (الجهة المختصة، التأمين، الشاغلين) ومراقبة حريق'], ['Closing all valves', 'إغلاق كل الصمامات'], ['Disabling the panel', 'تعطيل اللوحة']], 1,
    'NFPA 25 Chapter 15.', 'NFPA 25 الفصل 15.'),
  Q('a23', 'tech', 'VESDA "Alert / Action / Fire1 / Fire2" levels are typically used to…', 'مستويات VESDA "تنبيه / إجراء / حريق1 / حريق2" تُستخدم عادة لـ…',
    [['Measure temperature', 'قياس الحرارة'], ['Stage the response from early warning to suppression release', 'تدريج الاستجابة من التحذير المبكر إلى إطلاق الإطفاء'], ['Control the lift', 'التحكم بالمصعد'], ['Test batteries', 'اختبار البطاريات']], 1,
    'Very early warning allows intervention before a fire develops.', 'التحذير المبكر جداً يسمح بالتدخل قبل تطور الحريق.'),
  Q('a24', 'tech', 'Maximum transport time for aspirating smoke detection from the farthest hole (NFPA 72):', 'أقصى زمن انتقال لكشف الدخان بالشفط من أبعد فتحة (NFPA 72):',
    [['30 s', '30 ث'], ['60 s', '60 ث'], ['120 s', '120 ث'], ['300 s', '300 ث']], 2,
    'NFPA 72 §17.7.3.6.2.2 — 120 s maximum.', 'NFPA 72 — 120 ثانية بحد أقصى.'),
  Q('a25', 'tech', 'A double-interlock pre-action system admits water to the piping when…', 'نظام ما قبل الفعل مزدوج التعشيق يُدخل المياه إلى الأنابيب عندما…',
    [['A detector operates', 'يعمل كاشف'], ['A sprinkler opens', 'يفتح رشاش'], ['BOTH a detector operates AND piping air pressure is lost', 'يعمل كاشف وتفقد الأنابيب ضغط الهواء معاً'], ['Either one', 'أيهما']], 2,
    'Used for freezers / high-value areas to avoid accidental water.', 'يُستخدم للثلاجات والمناطق عالية القيمة لتجنب المياه العرضية.'),
  Q('a26', 'install', 'Horn/strobe wall mounting height (NFPA 72):', 'ارتفاع تركيب البوق/الوميض على الجدار (NFPA 72):',
    [['1.2–1.5 m', '1.2–1.5 م'], ['2.03–2.44 m above floor', '2.03–2.44 م فوق الأرض'], ['At the ceiling only', 'على السقف فقط'], ['Any height', 'أي ارتفاع']], 1,
    'NFPA 72 §18.5.5.1: 80–96 in (2.03–2.44 m) AFF.', 'NFPA 72 §18.5.5.1: 80–96 إنش.'),
  Q('a27', 'install', 'Where is the EOL resistor of a monitor module IDC installed?', 'أين تُركّب مقاومة نهاية الخط لدائرة الإدخال في وحدة المراقبة؟',
    [['Inside the module', 'داخل الوحدة'], ['At the last device of the circuit', 'عند آخر جهاز على الدائرة'], ['In the panel', 'في اللوحة'], ['It is not needed', 'غير مطلوبة']], 1,
    'Otherwise the field wiring is not supervised.', 'وإلا فلن تكون التوصيلات الميدانية مراقبة.'),
  Q('a28', 'install', 'Control modules (relays) for emergency control functions must be located within … of the controlled equipment.', 'يجب أن تكون وحدات التحكم لوظائف التحكم الطارئ ضمن … من المعدات المتحكم بها.',
    [['0.9 m (3 ft)', '0.9 م (3 قدم)'], ['10 m', '10 م'], ['Same floor', 'نفس الطابق'], ['Anywhere', 'أي مكان']], 0,
    'NFPA 72 §21.2.4.', 'NFPA 72 §21.2.4.'),
  Q('a29', 'commission', 'Insulation resistance of fire-alarm cabling before connecting devices is typically checked with:', 'مقاومة العزل لكابلات إنذار الحريق قبل توصيل الأجهزة تُفحص عادة بـ:',
    [['A 500 V insulation tester (Megger), ≥ 1 MΩ', 'جهاز فحص عزل 500 فولت (ميجر)، ≥ 1 ميجا أوم'], ['A clamp meter', 'أمبير كلامب'], ['A smoke aerosol', 'بخاخ دخان'], ['A dB meter', 'جهاز ديسيبل']], 0,
    'Disconnect devices first — the test voltage can damage electronics.', 'افصل الأجهزة أولاً — فجهد الاختبار قد يتلف الإلكترونيات.'),
  Q('a30', 'commission', 'Which document records that the system was installed and tested per NFPA 72?', 'أي وثيقة تسجل أن النظام رُكّب واختُبر وفق NFPA 72؟',
    [['Record of Completion', 'سجل الإنجاز (Record of Completion)'], ['Purchase order', 'أمر الشراء'], ['Invoice', 'الفاتورة'], ['Datasheet', 'نشرة البيانات']], 0,
    'NFPA 72 §7.5.6 — completed and signed at acceptance.', 'NFPA 72 §7.5.6 — تُكمل وتُوقع عند الاستلام.'),
];
