#!/usr/bin/env node
// Vendor license tool.
//   node tools/license-tool.mjs init                      → create your signing key pair (run ONCE, keep keys/private.pem secret)
//   node tools/license-tool.mjs issue --name "Univ. of Jordan" --org "Civil Eng." --plan annual [--machine XXXX-XXXX-XXXX-XXXX] [--seats 30] [--email a@b.c]
//   node tools/license-tool.mjs verify <key>
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const privFile = path.join(root, 'keys', 'private.pem');
const pubFile = path.join(root, 'electron', 'license-public.js');
const b64u = (buf) => Buffer.from(buf).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

const args = process.argv.slice(2);
const cmd = args[0];
const opt = (k, d) => { const i = args.indexOf(`--${k}`); return i >= 0 ? args[i + 1] : d; };

if (cmd === 'init') {
  if (fs.existsSync(privFile) && !args.includes('--force')) { console.error('keys/private.pem already exists (use --force to replace — old licenses will stop working).'); process.exit(1); }
  const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519');
  fs.mkdirSync(path.dirname(privFile), { recursive: true });
  fs.writeFileSync(privFile, privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600 });
  const pem = publicKey.export({ type: 'spki', format: 'pem' });
  fs.writeFileSync(pubFile, `// Public key used to verify license signatures (generated by tools/license-tool.mjs init)\nmodule.exports = { PUBLIC_KEY: ${JSON.stringify(pem)} };\n`);
  console.log('✓ Key pair created.\n  Private key: keys/private.pem   (KEEP SECRET, back it up, never commit it)\n  Public key : electron/license-public.js (rebuild the app after this)');
} else if (cmd === 'issue') {
  if (!fs.existsSync(privFile)) { console.error('Run "npm run license:init" first.'); process.exit(1); }
  const plan = opt('plan', 'annual');
  if (!['monthly', 'annual'].includes(plan)) { console.error('--plan must be monthly or annual'); process.exit(1); }
  const months = +opt('months', plan === 'annual' ? 12 : 1);
  const start = opt('start') ? new Date(opt('start')) : new Date();
  const exp = new Date(start); exp.setMonth(exp.getMonth() + months); exp.setDate(exp.getDate() + 1);
  const payload = {
    id: crypto.randomUUID(), name: opt('name', 'Customer'), org: opt('org', ''), email: opt('email', ''), plan,
    seats: +opt('seats', 1), issued: new Date().toISOString(), expires: exp.toISOString(), machine: opt('machine', '*'),
  };
  const head = `FTW1.${b64u(JSON.stringify(payload))}`;
  const sig = crypto.sign(null, Buffer.from(head), crypto.createPrivateKey(fs.readFileSync(privFile)));
  const key = `${head}.${b64u(sig)}`;
  fs.mkdirSync(path.join(root, 'keys', 'issued'), { recursive: true });
  fs.appendFileSync(path.join(root, 'keys', 'issued', 'ledger.csv'), `${payload.issued},${payload.id},"${payload.name}","${payload.org}",${plan},${payload.seats},${payload.expires},${payload.machine}\n`);
  console.log(JSON.stringify(payload, null, 2));
  console.log('\nLICENSE KEY:\n' + key);
} else if (cmd === 'verify') {
  const { verifyKey } = require(path.join(root, 'electron', 'license.js'));
  console.log(verifyKey(args[1], opt('machine', undefined)));
} else {
  console.log('Usage: license-tool.mjs init | issue --name N --plan monthly|annual [--machine ID] [--seats N] [--months N] | verify <key>');
}
